# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  containerRegistryServiceConnection: Docker_Motish
  imageRepository: motish12/front-end
  tag: azure_test

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: 'Install Packages'
  inputs:
    command: 'install'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: 'run build'

- task: CopyFiles@2
  inputs:
    Contents: |
      dist/**
      nginx.conf
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'dist'
    publishLocation: 'pipeline'

- task: Docker@2
  inputs:
    command: login
    containerRegistry: $(containerRegistryServiceConnection)

- task: Docker@2
  displayName: Build an image
  inputs:
    command: build
    buildContext: $(Build.ArtifactStagingDirectory)
    containerRegistry: $(containerRegistryServiceConnection)
    repository: $(imageRepository)
    tags: |
      $(tag)
    Dockerfile: /**/Dockerfile_Azure_CI

- task: Docker@2
  displayName: Push image
  inputs:
    containerRegistry: $(containerRegistryServiceConnection)
    repository: $(imageRepository)
    command: push
    tags: |
      $(tag)