FROM nginx:alpine

COPY ./dist/front-end /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY ./startup.sh /startup.sh

ENTRYPOINT [ "/startup.sh" ]
CMD ["nginx", "-g", "daemon off;"]
